[package]
name = "molecule"
version.workspace = true
authors.workspace = true
edition = "2021"
description = "Rust bindings for molecule."
homepage.workspace = true
repository.workspace = true
keywords = ["serialization"]
categories = ["encoding", "data-structures"]
license.workspace = true

[dependencies]
cfg-if.workspace = true
bytes.workspace = true
faster-hex = { version = "^0.6", optional = true }

[features]
default = ["std"]
std = ["bytes/std", "faster-hex"]
# Provide impls for bytes in no_std environment without depending on atomic
bytes_vec = []

[badges]
maintenance = { status = "experimental" }
