[package]
name = "molecule-ci-tests"
version.workspace = true
authors.workspace = true
edition = "2018"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "simple-example"
path = "src/simple-example.rs"

[dependencies]
molecule.workspace = true

[build-dependencies]
codegen.workspace = true
cc.workspace = true

[dev-dependencies]
molecule-tests-utils-rust.workspace = true
slices.workspace = true
proptest.workspace = true

[features]
default = ["std"]
std = ["molecule/std"]
