[package]
name = "molecule-tests-loader"
version.workspace = true
authors.workspace = true
edition = "2018"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
codegen.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
serde.workspace = true
faster-hex = "0.4.1"
property.workspace = true
