[package]
name = "tests"
version.workspace = true
authors.workspace = true
edition = "2021"
homepage.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
codegen-0_7_3.workspace = true
codegen_dev.workspace = true
molecule = { workspace = true, features = ["std"] }

[build-dependencies]
codegen-0_7_3.workspace = true
codegen_dev.workspace = true
molecule = { workspace = true, features = ["std"] }
