[package]
name = "lazy-reader-tests"
version.workspace = true
authors.workspace = true
edition = "2021"
homepage.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molecule.workspace = true
lazy_static.workspace = true
rand.workspace = true

[build-dependencies]
codegen.workspace = true
cc.workspace = true
