[package]
name = "molecule-tests-utils-rust"
version.workspace = true
authors.workspace = true
edition = "2018"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
codegen.workspace = true
tests-loader.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
serde_yaml.workspace = true
