[package]
name = "moleculec"
version.workspace = true
authors.workspace = true
edition = "2021"
description = "Schema compiler for molecule."
homepage.workspace = true
repository.workspace = true
keywords = ["molecule", "code-generation", "serialization"]
categories = [
    "parser-implementations",
    "development-tools",
    "encoding",
    "data-structures",
]
license.workspace = true

[[bin]]
name = "moleculec"
path = "src/compiler.rs"

[[bin]]
name = "moleculec-c"
path = "src/compiler-c.rs"

[[bin]]
name = "moleculec-rust"
path = "src/compiler-rust.rs"

[[bin]]
name = "moleculec-rust-lazy-reader"
path = "src/compiler-rust-lazy-reader.rs"

[dependencies]
clap.workspace = true
which.workspace = true
molecule_codegen.workspace = true

[badges]
maintenance = { status = "experimental" }
